Set correct capabilities for kwin-wayland. (Closes: #1102069)

diff --git a/debian/kwin-wayland.postinst b/debian/kwin-wayland.postinst
--- a/debian/kwin-wayland.postinst
+++ b/debian/kwin-wayland.postinst
@@ -4,12 +4,16 @@ set -e
 
 if [ "$1" = configure ]; then
     # Set the capabilities
-    if command -v setcap > /dev/null && \
-       setcap "CAP_SYS_RESOURCE=+ep" \
-            /usr/bin/kwin_wayland; then
-        echo "Sucessfully set capabilities for kwin_wayland"
+    if command -v setcap > /dev/null ; then
+        cap="CAP_SYS_NICE=+ep"
+        binary=/usr/bin/kwin_wayland
+        if ! setcap -v "${cap}" "${binary}" > /dev/null; then
+            setcap "${cap}" "${binary}" \
+                && echo "Successfully set ${cap} for ${binary}" \
+                || echo "Failed to set ${cap} for ${binary}" >&2
+        fi
     else
-        echo "Failed to set capabilities for kwin_wayland" >&2
+        echo "setcap command not found, failed to set capabilities for kwin_wayland" >&2
     fi
 fi
 
